FROM python:3.7.6-stretch AS base
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.7.6-slim-stretch AS final
COPY --from=base \
    /usr/local/lib/python3.7/site-packages/ \
    /usr/local/lib/python3.7/site-packages/
COPY --from=base /usr/local/bin /usr/local/bin

COPY . .

ENTRYPOINT [ "python", "main.py" ]
CMD []